[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyRomusaAI"
version = "0.4.3"
description = "A lightweight Python framework for creating simple AI chatbots with minimal code."
authors = [{name = "Robert Mureșan", email = "pyromusa.ai@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.25.0",
    "pandas>=2.1.0"
]
keywords = ["AI", "chatbot", "PyRomusaAI"]
license = {text = "Apache-2.0"}